name: Deploy Worker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      # url: ${{ github.ref == 'refs/heads/main' && steps.deploy.outputs.deployment-url || steps.deploy.outputs.deployment-url }}
      url: ${{steps.deploy.outputs.deployment-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup tinygo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.36.0"

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.0.0"
          command: ${{ github.ref == 'refs/heads/main' && 'deploy' || 'versions upload' }}

      - name: Print Wrangler command output
        env:
          CMD_OUTPUT: ${{ steps.deploy.outputs.command-output }}
        run: echo $CMD_OUTPUT
